create table data_pagination (
	id INT,
	descriptions VARCHAR(50)
);
insert into data_pagination (id, descriptions) values (1, '3-methylglutaconic aciduria');
insert into data_pagination (id, descriptions) values (2, 'Other superficial bite of left elbow, initial encounter');
insert into data_pagination (id, descriptions) values (3, 'Strain of musc/tend anterior grp at low leg level, right leg');
insert into data_pagination (id, descriptions) values (4, 'Unspecified Eustachian salpingitis, unspecified ear');
insert into data_pagination (id, descriptions) values (5, 'Poisn by unsp primarily systemic and hematolog agent, acc');
insert into data_pagination (id, descriptions) values (6, 'Disp fx of less trochanter of r femr, 7thN');
insert into data_pagination (id, descriptions) values (7, 'Poisoning by MAO inhib antidepress, undetermined, sequela');
insert into data_pagination (id, descriptions) values (8, 'Complex tear of lateral meniscus, current injury, left knee');
insert into data_pagination (id, descriptions) values (9, 'Other conditions originating in the perinatal period');
insert into data_pagination (id, descriptions) values (10, 'Aortic aneurysm of unspecified site, ruptured');
insert into data_pagination (id, descriptions) values (11, 'Toxic effect of strychnine and its salts, self-harm');
insert into data_pagination (id, descriptions) values (12, 'Nondisp fx of unsp ulna styloid pro, 7thE');
insert into data_pagination (id, descriptions) values (13, 'Fall from, out of or through oth bldg, sequela');
insert into data_pagination (id, descriptions) values (14, 'Unspecified Eustachian salpingitis, bilateral');
insert into data_pagination (id, descriptions) values (15, 'War op w acc deton onboard marine weapons, civilian, subs');
insert into data_pagination (id, descriptions) values (16, 'Fx unsp prt of nk of unsp femr, 7thM');
insert into data_pagination (id, descriptions) values (17, 'Displaced transverse fx shaft of humerus, unsp arm, init');
insert into data_pagination (id, descriptions) values (18, 'Unsp injury of long flexor musc/fasc/tend thmb at wrs/hnd lv');
insert into data_pagination (id, descriptions) values (19, 'Japanese encephalitis');
insert into data_pagination (id, descriptions) values (20, 'Evidence of alcohol involv determined by blood alcohol level');
insert into data_pagination (id, descriptions) values (21, 'Frostbite w tissue necrosis of unsp finger(s), subs encntr');
insert into data_pagination (id, descriptions) values (22, 'Snow-skier colliding with stationary object');
insert into data_pagination (id, descriptions) values (23, 'Unsp inj flexor musc/fasc/tend unsp fngr at wrs/hnd lv, sqla');
insert into data_pagination (id, descriptions) values (24, 'Other superficial bite of scrotum and testes, init encntr');
insert into data_pagination (id, descriptions) values (25, 'Frostbite with tissue necrosis of left toe(s), init encntr');
insert into data_pagination (id, descriptions) values (26, 'Disp fx of med condyle of l femur, init for opn fx type I/2');
insert into data_pagination (id, descriptions) values (27, 'Traumatic hemothorax, subsequent encounter');
insert into data_pagination (id, descriptions) values (28, 'Pasngr in 3-whl mv inj in nonclsn trnsp acc in traf, init');
insert into data_pagination (id, descriptions) values (29, 'Open bite of left buttock, subsequent encounter');
insert into data_pagination (id, descriptions) values (30, 'Corrosion of second degree of right ankle and foot, init');
insert into data_pagination (id, descriptions) values (31, 'Physeal arrest, femur, unspecified');
insert into data_pagination (id, descriptions) values (32, 'Displ spiral fx shaft of humer, r arm, 7thD');
insert into data_pagination (id, descriptions) values (33, 'Unsp inj unsp blood vess at hip and thi lev, left leg, subs');
insert into data_pagination (id, descriptions) values (34, 'Non-pressure chronic ulcer of skin, not elsewhere classified');
insert into data_pagination (id, descriptions) values (35, 'Unsp comp of fb acc left in body following punctr/cath');
insert into data_pagination (id, descriptions) values (36, 'Nondisp oblique fx shaft of unsp tibia, 7thJ');
insert into data_pagination (id, descriptions) values (37, 'Oth fx lower end of unsp tibia, init for opn fx type I/2');
insert into data_pagination (id, descriptions) values (38, 'Person injured in collision betw car and hv veh, subs');
insert into data_pagination (id, descriptions) values (39, 'Unspecified subluxation of left radial head, sequela');
insert into data_pagination (id, descriptions) values (40, 'Fracture of angle of right mandible, 7thD');
insert into data_pagination (id, descriptions) values (41, 'Primary inadequate contractions');
insert into data_pagination (id, descriptions) values (42, 'Displ oblique fx shaft of unsp femr, 7thJ');
insert into data_pagination (id, descriptions) values (43, 'Nondisplaced oblique fracture of shaft of right tibia');
insert into data_pagination (id, descriptions) values (44, 'Path fracture in neoplastic disease, right hand, sequela');
insert into data_pagination (id, descriptions) values (45, 'Burn of unspecified degree of right ankle, subs encntr');
insert into data_pagination (id, descriptions) values (46, 'Disp fx of l tibial tuberosity, 7thQ');
insert into data_pagination (id, descriptions) values (47, 'Tuberculous peripheral lymphadenopathy');
insert into data_pagination (id, descriptions) values (48, 'Supervision of young multigravida, first trimester');
insert into data_pagination (id, descriptions) values (49, 'Nondisp fx of prox phalanx of l little fngr, init for opn fx');
insert into data_pagination (id, descriptions) values (50, 'Non-prs chronic ulcer oth prt right foot w fat layer exposed');
insert into data_pagination (id, descriptions) values (51, 'Longitudinal reduction defect of tibia, bilateral');
insert into data_pagination (id, descriptions) values (52, 'Low-tension glaucoma, bilateral, stage unspecified');
insert into data_pagination (id, descriptions) values (53, 'Partial traumatic amp of unsp lower leg, level unsp, init');
insert into data_pagination (id, descriptions) values (54, 'Obturator dislocation of right hip, initial encounter');
insert into data_pagination (id, descriptions) values (55, 'Food in resp tract, part unsp causing oth injury, sequela');
insert into data_pagination (id, descriptions) values (56, 'Burn of first degree of right forearm, subsequent encounter');
insert into data_pagination (id, descriptions) values (57, 'Path fx in oth disease, r ankle, subs for fx w delay heal');
insert into data_pagination (id, descriptions) values (58, 'Oth meniscus derang, posterior horn of lat mensc, left knee');
insert into data_pagination (id, descriptions) values (59, 'Nondisp longitud fx l patella, 7thH');
insert into data_pagination (id, descriptions) values (60, 'Disp fx of middle third of navic bone of l wrist, sequela');
insert into data_pagination (id, descriptions) values (61, 'Corrosion of second degree of left toe(s) (nail), sequela');
insert into data_pagination (id, descriptions) values (62, 'Driver of 3-whl mv injured in collision w hv veh in traf');
insert into data_pagination (id, descriptions) values (63, 'Encounter for screening for malignant neoplasm of cervix');
insert into data_pagination (id, descriptions) values (64, 'Benign neoplasm of connctv/soft tiss of lower limb, inc hip');
insert into data_pagination (id, descriptions) values (65, 'Unspecified physeal fracture of right metatarsal, 7thG');
insert into data_pagination (id, descriptions) values (66, 'Assault by antipersonnel bomb');
insert into data_pagination (id, descriptions) values (67, 'Milt op involving oth conventional warfare, civilian, init');
insert into data_pagination (id, descriptions) values (68, 'Reiter''s disease, left hip');
insert into data_pagination (id, descriptions) values (69, 'Urticaria');
insert into data_pagination (id, descriptions) values (70, 'Oth fx shaft of rad, r arm, subs for clos fx w routn heal');
insert into data_pagination (id, descriptions) values (71, 'Fx unsp tarsal bone(s) of unsp foot, subs for fx w malunion');
insert into data_pagination (id, descriptions) values (72, 'Athscl unsp type bypass of the extremities w rest pain');
insert into data_pagination (id, descriptions) values (73, 'Mtrcy driver injured in collision w unsp mv in traf, init');
insert into data_pagination (id, descriptions) values (74, 'Unsp tear of unsp meniscus, current injury, left knee, init');
insert into data_pagination (id, descriptions) values (75, 'Polyhydramnios, third trimester, fetus 1');
insert into data_pagination (id, descriptions) values (76, 'Unsp fracture of right toe(s), subs for fx w routn heal');
insert into data_pagination (id, descriptions) values (77, 'Unspecified atrioventricular block');
insert into data_pagination (id, descriptions) values (78, 'Nondisp fx of l radial styloid pro, 7thG');
insert into data_pagination (id, descriptions) values (79, 'Drug/chem diab w diab mclr edma, resolved fol trtmt, l eye');
insert into data_pagination (id, descriptions) values (80, 'Pnctr w/o foreign body of right thumb w damage to nail, subs');
insert into data_pagination (id, descriptions) values (81, 'Poisoning by chloramphenicol group, self-harm, init');
insert into data_pagination (id, descriptions) values (82, 'Unspecified disorder of vestibular function, bilateral');
insert into data_pagination (id, descriptions) values (83, 'Encounter for administrative examinations, unspecified');
insert into data_pagination (id, descriptions) values (84, 'Nondisplaced unsp fracture of right great toe, sequela');
insert into data_pagination (id, descriptions) values (85, 'Foreign body in small intestine, sequela');
insert into data_pagination (id, descriptions) values (86, 'Displaced fracture of right ulna styloid process, sequela');
insert into data_pagination (id, descriptions) values (87, 'Corrosion of third degree of right shoulder, subs encntr');
insert into data_pagination (id, descriptions) values (88, 'Unspecified injury of left external jugular vein, sequela');
insert into data_pagination (id, descriptions) values (89, 'Poisoning by calcium-channel blockers, assault');
insert into data_pagination (id, descriptions) values (90, 'Unsp pedl cyclst injured in clsn w ped/anml nontraf, init');
insert into data_pagination (id, descriptions) values (91, 'Mumps meningitis');
insert into data_pagination (id, descriptions) values (92, 'Hemorrhagic fever with renal syndrome');
insert into data_pagination (id, descriptions) values (93, 'Other specified injury of popliteal vein, left leg, sequela');
insert into data_pagination (id, descriptions) values (94, 'Unspecified open wound of right elbow, subsequent encounter');
insert into data_pagination (id, descriptions) values (95, 'Occup of pk-up/van inj in clsn w ped/anml nontraf, sequela');
insert into data_pagination (id, descriptions) values (96, 'Poisoning by antipruritics, undetermined');
insert into data_pagination (id, descriptions) values (97, 'Occupant of aircraft injured in oth air transport acc, subs');
insert into data_pagination (id, descriptions) values (98, 'Coma scale, eyes open, never');
insert into data_pagination (id, descriptions) values (99, 'Fx rad/ulna fol insrt ortho implnt/prosth/bone plt, unsp arm');
insert into data_pagination (id, descriptions) values (100, 'Disease of pulmonary vessels, unspecified');
